package interfaces.parqueadero;
import java.text.DecimalFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import java.math.BigDecimal;
import java.math.RoundingMode;

import com.parqueaderosistemas.jdbc.*;
import com.parqueaderosistemas.beans.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
/**
 *
 * @author JONATHAN
 */
public class RegPrecios extends javax.swing.JFrame {
    private JComboBox opcionesVeh;
    
    private String tipoVehiculo;
    private double valorHora;
    private double valorMinuto;
    /**
     * Creates new form RegPrecios
     */
    public RegPrecios() {
        initComponents();
        this.setBounds(0,0,553,400);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        opcionesVeh = new JComboBox();
        opcionesVeh.setBounds(250,170,140,30);
        add(opcionesVeh);
        
        //opcionesVeh.addItem("...");
        opcionesVeh.addItem("Carro");
        opcionesVeh.addItem("Vehiculo Pesado");
        opcionesVeh.addItem("Moto");
        
        opcionesVeh.addActionListener(new java.awt.event.ActionListener(){
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt){
                opcionesVehActionPerformed(evt);
            }

        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textValor = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        botonGuardar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/parqueadero/images/cintaP.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/parqueadero/images/parkingCP.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel4.setText("ARQUEADERO");

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel6.setText("Registro de Precios por hora");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/parqueadero/images/cintaP.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Valor:       $");

        textValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValorActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tipo Vehiculo:");

        jButton2.setText("<|");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        botonGuardar1.setText("Cancelar");
        botonGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textValor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(botonGuardar1)
                        .addGap(169, 169, 169))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonGuardar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void opcionesVehActionPerformed(java.awt.event.ActionEvent evt){

            //JOptionPane.showMessageDialog(null,"Funciono");
            tipoVehiculo = opcionesVeh.getSelectedItem().toString();
            //valorHora = Double.parseDouble(textValor.getText());
            int indicePrimario = 0;
            if(tipoVehiculo.equals("Carro")){
                indicePrimario = 1;
            }else if(tipoVehiculo.equals("Vehiculo Pesado")){
                indicePrimario = 2;
            }else if(tipoVehiculo.equals("Moto")){
                indicePrimario = 3;
            }
            
            PreciosJDBC preciosJDBC = new PreciosJDBC();
            Precio precioRec = preciosJDBC.select(indicePrimario);
            textValor.setText(Double.toString(precioRec.getValor()));
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        parqueaderoBienvenida pb = new parqueaderoBienvenida();
        pb.setBounds(0,0,598,313);
        pb.setVisible(true);
        pb.setResizable(false);
        pb.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textValorActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        boolean banderaNum= false;
        if(textValor.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor ingresa un valor válido");
        }

        for(int i=0;i<textValor.getText().length();i++){
                int j=i+1;
                if(j<=textValor.getText().length()){
                    //System.out.println("*******"+textValor.getText().substring(0,1));
                    
                        if(!textValor.getText().substring(i,j).equals("0") &&
                                !textValor.getText().substring(i,j).equals("1") && 
                                !textValor.getText().substring(i,j).equals("2") && 
                                !textValor.getText().substring(i,j).equals("3") &&
                                !textValor.getText().substring(i,j).equals("4") &&
                                !textValor.getText().substring(i,j).equals("5") &&
                                !textValor.getText().substring(i,j).equals("6") &&
                                !textValor.getText().substring(i,j).equals("7") &&
                                !textValor.getText().substring(i,j).equals("8") &&
                                !textValor.getText().substring(i,j).equals("9") &&
                                !textValor.getText().substring(i,j).equals(".")){
                                
                            JOptionPane.showMessageDialog(null,"Por favor ingresa solo numeros");
                            banderaNum=false;
                            return;
                        }else{
                            banderaNum=true;
                        } 
                }                        
            }
        if(banderaNum){
            tipoVehiculo = opcionesVeh.getSelectedItem().toString();
            valorHora = Double.parseDouble(textValor.getText());
            int indicePrimario = 0;
            if(tipoVehiculo.equals("Carro")){
                indicePrimario = 1;
            }else if(tipoVehiculo.equals("Vehiculo Pesado")){
                indicePrimario = 2;
            }else if(tipoVehiculo.equals("Moto")){
                indicePrimario = 3;
            }
            
            //String vH = Double.toString(valorHora);
            
            Precio precio = new Precio();
            precio.setTipo(tipoVehiculo);
            precio.setValor(valorHora);
            precio.setIndice(indicePrimario);
            
            PreciosJDBC preciosJDBC = new PreciosJDBC();
            preciosJDBC.update(precio);
            
            JOptionPane.showMessageDialog(null, "Valor Registrado");
            /*
            
            valorMinuto = valorHora /60;
            BigDecimal bd = new BigDecimal(valorMinuto);
            bd = bd.setScale(2, RoundingMode.CEILING);
            valorMinuto = bd.doubleValue();
            String vM = Double.toString(valorMinuto);
            */
            
            
            //System.out.println("Veh:" + tipoVehiculo +"\nHora:" + vH + "\nMinuto:" + vM +"\nHORA:" + (valorMinuto*60));
        }
        
        
        
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardar1ActionPerformed
        parqueaderoBienvenida pb = new parqueaderoBienvenida();
        pb.setBounds(0,0,598,313);
        pb.setVisible(true);
        pb.setResizable(false);
        pb.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_botonGuardar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegPrecios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegPrecios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonGuardar1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField textValor;
    // End of variables declaration//GEN-END:variables
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("interfaces/parqueadero/images/parkingC.png"));
        return retValue;
    }
}
